env:
  commonjs: true
  es2021: true
  node: true
  mocha: true
  browser: true
parser: '@typescript-eslint/parser'
extends:
  - eslint:recommended
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  # - google
plugins:
  - '@typescript-eslint'
  - prettier
parserOptions:
  ecmaVersion: 12
rules: { 'prettier/prettier': 'error' }
