version: "3.9"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    expose:
      - 5432
    ports:
      - 5434:5432
  todo-svc:
    image: ghcr.io/super-bootcamp-2021/todo-svc:latest
    command:
      - service:start
    depends_on:
      - postgres
    environment:
      todo_database__host: postgres
      todo_database__port: 5432
      todo_database__username: postgres
      todo_database__password: postgres
      todo_database__database: todo
      todo_server__port: 80
    ports:
      - 9000:80
